version: '3.8'

services:
  # API Gateway
  gateway:
    build:
      context: ./src/ApiGateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - usersapi
      - salesapi
    networks:
      - app-network

  # Sales API
  salesapi:
    build:
      context: ./src/SalesApi
      dockerfile: Dockerfile
    ports:
      - "5013:5013"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Port=5432;Database=${SALES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - RabbitMQ__Host=${RBMQHOST}
      - RabbitMQ__Username=${RBMQUSER}
      - RabbitMQ__Password=${RBMQPASSWORD}
    networks:
      - app-network
    depends_on:
      - rabbitmq

  # Users API
  usersapi:
    build:
      context: ./src/UsersApi
      dockerfile: Dockerfile
    ports:
      - "5012:5012"
    environment:
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Port=5432;Database=${USERS_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    networks:
      - app-network

    # Users API
  inventoryapi:
    build:
      context: ./src/InventoryApi
      dockerfile: Dockerfile
    ports:
      - "5014:5014"
    environment:
       ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Port=5432;Database=${INVENTORY_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - RabbitMQ__Host=${RBMQHOST}
      - RabbitMQ__Username=${RBMQUSER}
      - RabbitMQ__Password=${RBMQPASSWORD}
    networks:
      - app-network
    depends_on:
      - rabbitmq

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

networks:
  app-network:
