version: '3.8'
services:
  usersapi:
    build:
      context: ./src/UsersAPI
      dockerfile: Dockerfile
    ports:
      - "5012:5012"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=usersdb;Username=postgres;Password=postgres
    depends_on:
      - db
    networks:
      - users-network

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - users-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  users-network:

volumes:
  postgres-data:
